
name: Schedule Web Access

on:
  schedule:
    # 定时任务表达式，每2小时执行一次
    - cron: '0 */2 * * *'

jobs:
  access-website:
    runs-on: ubuntu-latest
    steps:
      - name: Access Website
        run: |
          curl http://tvi.ccwu.cc/tv/1.php
